# -*- coding: utf-8 -*-
from odoo import models, fields, api, _
from odoo.exceptions import UserError


class VansalesReceipt(models.Model):
    """
    Van Sales Receipt – the payment collection document.

    A receipt can allocate collected cash/card against one or more posted
    customer invoices (account.move of type out_invoice).  Payment method
    determines which journal is used from the van configuration.

    States:
        draft         – editable, not yet posted.
        pending_sync  – created offline, waiting for server-side posting.
        posted        – payment posted and (optionally) reconciled.
        cancelled     – cancelled without effect.

    TODO: implement full payment creation and reconciliation in action_post.
    """
    _name = 'vansales.receipt'
    _description = 'Van Sales Receipt'
    _rec_name = 'name'
    _order = 'date desc, id desc'

    # ── Identity ──────────────────────────────────────────────────────────────
    name = fields.Char(
        string='Receipt Reference',
        readonly=True,
        copy=False,
        default='/',
    )
    company_id = fields.Many2one(
        'res.company',
        string='Company',
        required=True,
        default=lambda self: self.env.company,
    )
    state = fields.Selection(
        selection=[
            ('draft', 'Draft'),
            ('pending_sync', 'Pending Sync'),
            ('posted', 'Posted'),
            ('cancelled', 'Cancelled'),
        ],
        string='Status',
        default='draft',
        required=True,
        tracking=True,
        index=True,
    )

    # ── Offline / PWA ─────────────────────────────────────────────────────────
    external_uid = fields.Char(
        string='External UID',
        index=True,
        copy=False,
        help='UUID generated by mobile device; used for idempotent sync.',
    )
    device_id = fields.Char(
        string='Device ID',
        copy=False,
    )

    # ── Van / User ────────────────────────────────────────────────────────────
    van_id = fields.Many2one(
        'vansales.van',
        string='Van',
        required=True,
        index=True,
    )
    user_id = fields.Many2one(
        'res.users',
        string='Salesperson',
        required=True,
        default=lambda self: self.env.user,
    )
    partner_id = fields.Many2one(
        'res.partner',
        string='Customer',
        required=True,
        index=True,
    )
    sale_order_id = fields.Many2one(
        'sale.order',
        string='Sale Order',
        index=True,
    )

    # ── Dates ─────────────────────────────────────────────────────────────────
    date = fields.Datetime(
        string='Date',
        required=True,
        default=fields.Datetime.now,
    )

    # ── Currency / amount ─────────────────────────────────────────────────────
    currency_id = fields.Many2one(
        'res.currency',
        string='Currency',
        required=True,
        default=lambda self: self.env.company.currency_id,
    )
    amount_total = fields.Monetary(
        string='Total Amount',
        currency_field='currency_id',
        compute='_compute_amount_total',
        store=True,
    )

    # ── Payment method + journal ───────────────────────────────────────────────
    payment_method = fields.Selection(
        selection=[
            ('cash', 'Cash'),
            ('bank', 'Bank Transfer'),
            ('visa', 'Visa'),
            ('mastercard', 'Mastercard'),
        ],
        string='Payment Method',
        required=True,
        default='cash',
    )
    journal_id = fields.Many2one(
        'account.journal',
        string='Journal',
        compute='_compute_journal_id',
        store=True,
        readonly=False,
        help='Resolved from van configuration based on payment method. '
             'Can be overridden manually.',
    )

    # ── Receipt lines (invoice allocations) ───────────────────────────────────
    line_ids = fields.One2many(
        'vansales.receipt.line',
        'receipt_id',
        string='Invoice Allocations',
    )

    # ── Computes ──────────────────────────────────────────────────────────────
    @api.depends('line_ids.amount_applied')
    def _compute_amount_total(self):
        for rec in self:
            rec.amount_total = sum(rec.line_ids.mapped('amount_applied'))

    @api.depends('payment_method', 'van_id')
    def _compute_journal_id(self):
        for rec in self:
            van = rec.van_id
            if not van:
                rec.journal_id = False
                continue
            method = rec.payment_method
            if method == 'cash':
                rec.journal_id = van.cash_journal_id
            elif method == 'bank':
                rec.journal_id = van.bank_journal_id
            elif method == 'visa':
                rec.journal_id = van.visa_journal_id
            elif method == 'mastercard':
                rec.journal_id = van.mastercard_journal_id
            else:
                rec.journal_id = van.cash_journal_id

    # ── Actions ───────────────────────────────────────────────────────────────
    def action_post(self):
        """
        Post the receipt.

        Validates required fields, assigns the sequence number, and sets
        state to 'posted'.

        TODO: Create account.payment against journal_id for amount_total.
        TODO: Reconcile the payment against each line's invoice_id
              proportionally using amount_applied.
        """
        for rec in self:
            if rec.state not in ('draft', 'pending_sync'):
                raise UserError(_('Only draft or pending-sync receipts can be posted.'))
            if not rec.line_ids:
                raise UserError(_('Please add at least one invoice allocation line.'))
            if not rec.journal_id:
                raise UserError(
                    _('No journal found. Please configure the payment journals on the van.')
                )
            if rec.amount_total <= 0:
                raise UserError(_('Receipt amount must be greater than zero.'))

            # Assign sequence on first post
            if rec.name == '/':
                rec.name = self.env['ir.sequence'].next_by_code('vansales.receipt') or '/'

            # TODO: Create and post account.payment:
            #   payment = self.env['account.payment'].create({...})
            #   payment.action_post()

            # TODO: Reconcile against invoices:
            #   for line in rec.line_ids:
            #       ...reconcile payment move lines with invoice move lines...

            rec.state = 'posted'

    def action_cancel(self):
        for rec in self:
            if rec.state == 'posted':
                raise UserError(_('Posted receipts cannot be cancelled directly. Please create a reversal.'))
            rec.state = 'cancelled'

    def action_reset_draft(self):
        for rec in self:
            if rec.state not in ('cancelled', 'pending_sync'):
                raise UserError(_('Only cancelled or pending-sync receipts can be reset to draft.'))
            rec.state = 'draft'

    # ── ORM overrides ─────────────────────────────────────────────────────────
    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', '/') == '/':
                # Defer sequence assignment to action_post for proper flow,
                # but assign a draft reference if not coming from sync.
                pass
        return super().create(vals_list)


class VansalesReceiptLine(models.Model):
    """
    Van Sales Receipt Line – allocation of a collected amount against an invoice.

    Each line links a posted customer invoice to the portion of the receipt
    amount that covers it.
    """
    _name = 'vansales.receipt.line'
    _description = 'Van Sales Receipt Line'

    receipt_id = fields.Many2one(
        'vansales.receipt',
        string='Receipt',
        required=True,
        ondelete='cascade',
        index=True,
    )
    invoice_id = fields.Many2one(
        'account.move',
        string='Invoice',
        required=True,
        domain=[
            ('move_type', '=', 'out_invoice'),
            ('state', '=', 'posted'),
        ],
        help='Posted customer invoice being (partially) paid by this receipt.',
    )
    invoice_amount_residual = fields.Monetary(
        string='Invoice Balance',
        related='invoice_id.amount_residual',
        currency_field='currency_id',
        readonly=True,
    )
    currency_id = fields.Many2one(
        related='receipt_id.currency_id',
        store=True,
    )
    amount_applied = fields.Monetary(
        string='Amount Applied',
        required=True,
        currency_field='currency_id',
        help='Amount from this receipt allocated to this invoice.',
    )
