# -*- coding: utf-8 -*-
from odoo import models, fields, api, _


class SaleOrder(models.Model):
    """
    Extend sale.order with Van Sales fields.

    When `is_van_sale` is True the order is considered a van sale:
    - `warehouse_id` is driven by the van's warehouse.
    - `pricelist_id` is driven by the selected `sale_mode`.
    - No stock-blocking on confirmation (allow_negative_stock is always True
      for van sales as per business decision).
    """
    _inherit = 'sale.order'

    # ── Van Sale flag and references ──────────────────────────────────────────
    is_van_sale = fields.Boolean(
        string='Is Van Sale',
        default=False,
        index=True,
    )
    van_id = fields.Many2one(
        'vansales.van',
        string='Van',
        index=True,
        domain="[('active', '=', True)]",
        tracking=True,
    )
    sale_mode = fields.Selection(
        selection=[
            ('retail', 'Retail'),
            ('wholesale', 'Wholesale'),
        ],
        string='Sale Mode',
        default='retail',
    )

    # ── Stored related field for quick filtering ───────────────────────────────
    van_warehouse_id = fields.Many2one(
        'stock.warehouse',
        string='Van Warehouse',
        related='van_id.warehouse_id',
        store=True,
        readonly=True,
    )

    # ── Offline / PWA sync ────────────────────────────────────────────────────
    external_uid = fields.Char(
        string='External UID',
        index=True,
        copy=False,
        help='UUID generated by the mobile device; used for idempotent sync.',
    )
    source_device_id = fields.Char(
        string='Source Device ID',
        copy=False,
        help='Device identifier that created this order.',
    )

    # ── Linked receipts ───────────────────────────────────────────────────────
    van_receipt_ids = fields.One2many(
        'vansales.receipt',
        'sale_order_id',
        string='Van Receipts',
    )
    van_receipt_count = fields.Integer(
        string='Receipt Count',
        compute='_compute_van_receipt_count',
    )

    # ── Computes ──────────────────────────────────────────────────────────────
    def _compute_van_receipt_count(self):
        for order in self:
            order.van_receipt_count = len(order.van_receipt_ids)

    # ── Onchange ──────────────────────────────────────────────────────────────
    @api.onchange('van_id', 'sale_mode')
    def _onchange_van_and_mode(self):
        """
        Automatically set warehouse_id and pricelist_id from van + sale_mode.
        """
        if self.van_id:
            self.is_van_sale = True
            self.warehouse_id = self.van_id.warehouse_id

            if self.sale_mode == 'wholesale' and self.van_id.pricelist_wholesale_id:
                self.pricelist_id = self.van_id.pricelist_wholesale_id
            elif self.van_id.pricelist_retail_id:
                self.pricelist_id = self.van_id.pricelist_retail_id

    @api.onchange('is_van_sale')
    def _onchange_is_van_sale(self):
        if not self.is_van_sale:
            self.van_id = False
            self.sale_mode = 'retail'

    # ── Smart button ──────────────────────────────────────────────────────────
    def action_view_van_receipts(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _('Van Receipts'),
            'res_model': 'vansales.receipt',
            'view_mode': 'list,form',
            'domain': [('sale_order_id', '=', self.id)],
            'context': {
                'default_sale_order_id': self.id,
                'default_van_id': self.van_id.id,
                'default_partner_id': self.partner_id.id,
            },
        }

    # ── Override action_confirm ────────────────────────────────────────────────
    def action_confirm(self):
        """
        Confirm the sale order.

        For van sales we do NOT block confirmation based on stock levels
        (allow_negative_stock is the design choice for MVP).
        Standard Odoo confirmation flow is used unchanged.
        """
        # TODO: If allow_negative_stock is False on the van, add stock check here.
        return super().action_confirm()
